services:
  django:
    container_name: watchlog
    command: gunicorn watchlog.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-watchlog_db}
      POSTGRES_USER: ${POSTGRES_USER:-watchlog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-watchlog_password}
    networks:
      - watchlog
      - caddy
    restart: unless-stopped

  database:
    image: postgres:18-trixie
    container_name: watchlog-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-watchlog_db}
      POSTGRES_USER: ${POSTGRES_USER:-watchlog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-watchlog_password}
    networks:
      - watchlog
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

networks:
  watchlog:
  caddy:
    external: true

volumes:
  postgres_data:
