services:
  django:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: dev
      DJANGO_DEBUG_TOOLBAR: 1
    volumes:
      - ./src:/app

  frontend:
    build:
      context: ./frontend
      target: deps
    command: npm run dev -- --hostname 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs

  database:
    ports:
      - "127.0.0.1:5432:5432"
